services:
  - type: web
    name: facial-attendance
    env: python
    buildCommand: |
      apt-get update
      apt-get install -y libwebp-dev
      pip install -r requirements.txt
      python manage.py collectstatic --noinput
      python manage.py migrate
      python manage.py createsu
      python manage.py check
    startCommand: gunicorn core.wsgi:application
