services:
  - type: web
    name: facial-attendance
    runtime: python
    buildCommand: |
      apt-get update -qq
      apt-get install -y libwebp-dev libsm6 libxext6 libx11-6 libglib2.0-0 libgomp1 libgl1-mesa-glx ffmpeg libasound2
      if [ -f /usr/lib/x86_64-linux-gnu/libwebp.so.7 ]; then
        ln -sf /usr/lib/x86_64-linux-gnu/libwebp.so.7 /usr/lib/x86_64-linux-gnu/libwebp.so.6
      fi
      pip install -r requirements.txt
      python manage.py collectstatic --noinput
      python manage.py migrate
    startCommand: |
      python manage.py createsu
      gunicorn core.wsgi:application
