# Generated by Django 5.2.6 on 2025-08-25 00:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='face_encoding',
            new_name='lbph_model_data',
        ),
        migrations.RemoveField(
            model_name='course',
            name='lecturer',
        ),
        migrations.AlterField(
            model_name='attendancesession',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attendance.course'),
        ),
    ]
