# Generated by Django 5.2.6 on 2025-08-25 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0002_rename_face_encoding_student_lbph_model_data_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendancerecord',
            name='is_present',
            field=models.BooleanField(default=True),
        ),
    ]
