# Generated by Django 5.2.6 on 2025-08-28 02:19

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0004_course_lecturer'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='attendancerecord',
            unique_together={('session', 'student')},
        ),
        migrations.AddField(
            model_name='attendancerecord',
            name='status',
            field=models.CharField(choices=[('on_time', 'On Time'), ('late', 'Late')], default='on_time', max_length=10),
        ),
        migrations.AddField(
            model_name='attendancesession',
            name='end_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='attendancesession',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='attendancesession',
            name='start_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='attendancerecord',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records', to='attendance.attendancesession'),
        ),
        migrations.AlterField(
            model_name='attendancerecord',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records', to='attendance.student'),
        ),
        migrations.RemoveField(
            model_name='attendancerecord',
            name='is_present',
        ),
    ]
