# Generated by Django 5.2.6 on 2025-08-29 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0006_passwordreset'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='enrolled_students',
            field=models.ManyToManyField(blank=True, related_name='courses', to='attendance.student'),
        ),
    ]
