# Generated by Django 5.2.6 on 2025-09-11 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0007_course_enrolled_students'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='lbph_model_data',
        ),
        migrations.AddField(
            model_name='student',
            name='face_encodings_data',
            field=models.TextField(blank=True, help_text='JSON-encoded list of 128-dimensional face encodings from dlib.', null=True),
        ),
    ]
